remove env file and update build-validation.yml

diff --git a/.github/workflows/build-validation.yml b/.github/workflows/build-validation.yml
--- a/.github/workflows/build-validation.yml
+++ b/.github/workflows/build-validation.yml
@@ -14,46 +14,47 @@ jobs:
         with:
           labels: 'Needs Review'
 
-  review_required:
-    runs-on: ubuntu-latest
-    env:
-      RUN_REMOVE_LABEL: ${{ steps.check_labels.outputs.run_remove_label }}
-      PREVENT_MERGE: ${{ steps.check_labels.outputs.prevent_merge }}
-    steps:
-      - name: Check for Auto Merge or Needs Review
-        id: check_labels
-        if: ${{ contains(github.event.pull_request.labels.*.name, 'Auto Merge') || contains(github.event.pull_request.labels.*.name, 'Needs Review') }}
-        run: |
-          if [ "$(echo ${{ contains(github.event.pull_request.labels.*.name, 'Auto Merge') && contains(github.event.pull_request.labels.*.name, 'Needs Review') }})" == "true" ]; then
-            echo "Both labels present"
-            # code to be executed if both 'Auto Merge' and 'Needs Review' labels are present
-            echo "RUN_REMOVE_LABEL=true" >> env_file
-            echo "PREVENT_MERGE=false" >> env_file
-          else
-            echo "Only one label is present"
-            # code to be executed if only one of the labels is present
-            echo "RUN_REMOVE_LABEL=false" >> env_file
-            echo "PREVENT_MERGE=${{ contains(github.event.pull_request.labels.*.name, 'Needs Review') }}" >> env_file
-          fi
+review_required:
+  runs-on: ubuntu-latest
+  env:
+    RUN_REMOVE_LABEL: ${{ steps.check_labels.outputs.run_remove_label }}
+    PREVENT_MERGE: ${{ steps.check_labels.outputs.prevent_merge }}
+  steps:
+    - name: Check for Auto Merge or Needs Review
+      id: check_labels
+      if: ${{ contains(github.event.pull_request.labels.*.name, 'Auto Merge') || contains(github.event.pull_request.labels.*.name, 'Needs Review') }}
+      run: |
+        if [ "$(echo ${{ contains(github.event.pull_request.labels.*.name, 'Auto Merge') && contains(github.event.pull_request.labels.*.name, 'Needs Review') }})" == "true" ]; then
+          echo "Both labels present"
+          # code to be executed if both 'Auto Merge' and 'Needs Review' labels are present
+          echo "::set-env name=RUN_REMOVE_LABEL::true"
+          echo "::set-env name=PREVENT_MERGE::false"
+        else
+          echo "Only one label is present"
+          # code to be executed if only one of the labels is present
+          echo "::set-env name=RUN_REMOVE_LABEL::false"
+          echo "::set-env name=PREVENT_MERGE::${{ contains(github.event.pull_request.labels.*.name, 'Needs Review') }}"
+        fi
 
-      - name: Remove Label
-        if: ${{ env.RUN_REMOVE_LABEL == 'true' }}
-        uses: actions-ecosystem/action-remove-labels@v1
-        with:
-          labels: Needs Review
-        id: remove-label
+    - name: Remove Label
+      if: ${{ env.RUN_REMOVE_LABEL == 'true' }}
+      uses: actions-ecosystem/action-remove-labels@v1
+      with:
+        labels: Needs Review
+      id: remove-label
 
-      - name: Remove Label Failed
-        if: ${{ steps.remove-label.outcome == 'failure' }}
-        run: echo "Remove Label step failed" && exit 1
+    - name: Remove Label Failed
+      if: ${{ steps.remove-label.outcome == 'failure' }}
+      run: echo "Remove Label step failed" && exit 1
 
-      - name: Remove Label Succeeded
-        if: ${{ steps.remove-label.outcome == 'success' && steps.remove-label.outputs.code == '0' }}
-        run: echo "Remove Label step succeeded and returned code 0"
+    - name: Remove Label Succeeded
+      if: ${{ steps.remove-label.outcome == 'success' && steps.remove-label.outputs.code == '0' }}
+      run: echo "Remove Label step succeeded and returned code 0"
 
-      - name: Prevent Merge
-        if: ${{ env.RUN_REMOVE_LABEL == 'false' && env.PREVENT_MERGE == 'true' }}
-        run: echo "::error::Pull request cannot be merged when Needs Review label is assigned." && exit 1
+    - name: Prevent Merge
+      if: ${{ env.RUN_REMOVE_LABEL == 'false' && env.PREVENT_MERGE == 'true' }}
+      run: echo "::error::Pull request cannot be merged when Needs Review label is assigned." && exit 1
+
 
 
   validate:
